# SPDX-FileCopyrightText: 2025 Siemens AG
#
# SPDX-License-Identifier: Apache-2.0
#
# Author: Michael Adler <michael.adler@siemens.com>
no_progress = true
exclude_loopback = true
accept = ["200..=204", "429"]
exclude = ['^https://www\.gnu\.org', '^https://www\.mysql\.com']
